name: qiskit-examples
services:
  cli:
    image: giskit-examples
    pull_policy: never
    build:
      context: .
    volumes:
    # Persist working directory
    - ./workdir:/home/app
    # Mount source code for live editing
    - ./src:/opt/app/src
    entrypoint:
    - bash
