[project]
name = "qiskit-examples"
version = "0.1.0"
description = "Example usage of giskit library"
readme = "README.md"
authors = [
    { name = "Apiwat Chantawibul", email = "billiska@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "cython>=3.2.4",
    "matplotlib>=3.10.9",
    "numexpr>=2.14.1",
    "numpy>=2.4.6",
    "pylatexenc>=2.10",
    "pyscf>=2.13.0",
    "qiskit==1.4.5",
    "qiskit-aer==0.15.1",
    "qiskit-algorithms==0.3.1",
    "qiskit-experiments==0.8.2",
    "qiskit-ibm-runtime==0.29.0",
    "qiskit-nature==0.7.2",
    "qutip>=5.2.3",
    "sympy>=1.14.0",
    "tabulate>=0.10.0",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
]

[project.scripts]
qiskit-examples = "qiskit_examples:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"
